AWSTemplateFormatVersion: 2010-09-09
Description: Public-facing ELB listening on port 80 for path "/v1/*"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the load balancer will be deployed
    Default: vpc-2465842045826
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Subnets (multiple for HA) configured to allow internet access
    Default: subnet-27465297465,subnet-265924692
  HttpTrafficPort:
    Type: Number
    Description: The port for HTTP traffic
    Default: 80
  HttpTargetPort:
    Type: Number
    Description: The port for HTTP traffic to be forwarded to
    Default: 4318

Resources:
  PublicLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: public-load-balancer-security-group
      GroupDescription: Allow internet access to ELB on port 80
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HttpTrafficPort
          ToPort: !Ref HttpTrafficPort
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP traffic from anywhere
      Tags:
        - Key: Name
          Value: public-load-balancer-security-group

  PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: public-load-balancer
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - Ref: PublicLoadBalancerSecurityGroup
      Scheme: internet-facing
      IpAddressType: ipv4
      Type: application
      Tags:
        - Key: Name
          Value: public-load-balancer

  PublicLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref PublicLoadBalancer
      Port: !Ref HttpTrafficPort
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404
            ContentType: "text/plain"
            MessageBody: "Not Found"

  ListenerRuleForV1Path:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Priority: 1
      ListenerArn: !Ref PublicLoadBalancerListener
      Conditions:
        - Field: path-pattern
          Values: ["/v1/*"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref HttpTargetGroup

  HttpTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: http-target-group
      Port: !Ref HttpTargetPort
      Protocol: HTTP
      ProtocolVersion: HTTP1
      TargetType: ip
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 6
      # note that both of these (path, port) need to be exposed on the target Task
      HealthCheckPath: /healthcheck
      HealthCheckPort: 13133
      HealthCheckProtocol: HTTP
      HealthCheckEnabled: true
      Matcher:
        HttpCode: 200-499
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: http-target-group

Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the public load balancer
    Value: !GetAtt PublicLoadBalancer.DNSName
